name: build project
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
    branches: 
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: ls || npm ci
      - name: build
        run: npm run build
